### ISSUE TITLE
Discord can't detect presence

### ISSUE THREAD

**Issue by marchingon12** [satoqz/vscode-discord#135]
Although VSCode shows connection establised, discord itself does not detect vscode for some reason.

![Code_Cka8fvTx3b](https://user-images.githubusercontent.com/41235480/124494771-b8393a80-dda6-11eb-897f-375f12868ee9.png)
![Discord_p54p27QIOX](https://user-images.githubusercontent.com/41235480/124494931-f898b880-dda6-11eb-8372-f31155bcd857.png)

**Comment by satoqz** [comment]
Hello, everything is working as intended, discord is just a bit hard to understand in this case. The list of games in discord is created by discord itself looking for other processes, which has nothing to do with rich presence. Regardless, you have to check the "Display current activity" button for your presence to appear on your profile, even if it will never show up in the list.

**Comment by marchingon12** [comment]
> 
> 
> Hello, everything is working as intended, discord is just a bit hard to understand in this case. The list of games in discord is created by discord itself looking for other processes, which has nothing to do with rich presence. Regardless, you have to check the "Display current activity" button for your presence to appear on your profile, even if it will never show up in the list.

But as you can see, the toggle is set to "on". Am I the only person getting this result?

**Comment by satoqz** [comment]
Setting it to on will make the presence appear on your profile - not on that list

**Comment by marchingon12** [comment]
Ah that was what you meant. Well, it does not show up on my profile either.

**Comment by marchingon12** [comment]
Never mind it does work. I believe it might be because of Spotify being open at the same time. But after closing both Sportify and restarting VSCode, everything works fine now. Thnx for your time!

**Comment by satoqz** [comment]
The extension says its connected, you might be thrown off because discord has added an extra tab in the profile to display activities.

**Comment by marchingon12** [comment]
I don't think so, since I specifically checked on a server and clicked on my profile.
