### ISSUE TITLE
The extension won't turn off when I turn off the vscode

### ISSUE THREAD

**Issue by phamleduy04** [Satoqz/vscode-discord#17]
I turn off vscode on my laptop + pc but the Presence keeps going on.
Discord version: Discord Canary build 68164
Windows version: Windows 10 pro 64bit (build 2004)

**Comment by Satoqz** [comment]
If you properly end the vscode process, the rich presence should be gone just a few seconds afterwards. I'm guessing that you've got some background process launched through vscode that keeps it alive even when you close the window. This is most likely not an issue with the extension as fully ending the vscode process will literally force the ipc rpc connection to end.
