### ISSUE TITLE
[Question] Can't get YaDP to work

### ISSUE THREAD

**Issue by DatMayo** [Satoqz/vscode-discord#51]
Hey,

I installed your extension. But my statusbar does not change after I open VSCode & a project.
What can I do to get it to work?

**Comment by Satoqz** [comment]
Can you please provide more info on the exact clients that you're using? OS, vscode version, discord version, what does the bar of the extension on the bottom left in vscode say? Does it show at all?
Its quite impossible to help without knowing any information on the setup that the problem ist occuring with.

**Comment by DatMayo** [comment]
Hey,

OS: W10 x64
VSCode: 1.52.1 (system setup)
Discord: Stable 73712 (89c6c45)
Extension Bar: RPC Connected to Discord

Sry for the lack of information. I didn't know what to provide ;)

**Comment by Satoqz** [comment]
If it successfully indicates your connection as working there are usually 2 possible problems:

- You have your `game activity > display currently running game as a status message` inside of discord deactivated
- Another Rich Presence application is blocking the vscode one

Please check these and report back whether the issue has been solved :)

**Comment by DatMayo** [comment]
> You have your game activity > display currently running game as a status message inside of discord deactivated
Yes, thats the reason. Thx :)
