### ISSUE TITLE
Suggested programming language and icon

### ISSUE THREAD

**Issue by Neyunse** [Satoqz/vscode-discord#62]
Hello, could you add Ren'Py's language?
This is a logo I made, but I don't know if it fits well with the style of this extension. 
![renpy](https://user-images.githubusercontent.com/36079551/105897612-2824e700-5ff7-11eb-8a99-a98bb22f9618.png)

Ren'Py works with its own programming language based on Python.

**Comment by Satoqz** [comment]
Published as of b1aac2a4e927ec5f4115981f824019a4deb9c47c. Thank you for the suggestion + contribution, in my opinion your logo fit well into the scheme :smile:
