### ISSUE TITLE
VSCode Insiders

### ISSUE THREAD

**Issue by Sazzo** [satoqz/vscode-discord#91]
Heyo! Do you have plans to replace the standard VSCode icons (like, the logo) when the version of the user is using is the insiders?
Referring to these icons:
![image](https://user-images.githubusercontent.com/39680458/113074231-17ccec00-91a1-11eb-8584-6c63bfb7a8c9.png)

If you don't mind, I can open a pull request with the feature, it doesn't seem so difficult.

**Comment by satoqz** [comment]
Implemented as of eaf03c513f5a272f2b01aa0c381b59cda9b03b07 and 850b6d5bcaaf76b8597283a969ceec24310d0860, thank you for the suggestion :)
