### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by KREATIV-LSH** [satoqz/vscode-discord#94]
- Issue Type: `Bug`
- Extension Name: `yet-another-discord-presence`
- Extension Version: `1.5.1`
- OS Version: `Windows_NT x64 10.0.19041`
- VS Code version: `1.55.0`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 71,
		"activateCallTime": 45,
		"activateResolvedTime": 24,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "Satoqz.yet-another-discord-presence",
				"_lower": "satoqz.yet-another-discord-presence"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "RPC_CONNECTION_TIMEOUT"
		}
	]
}
```

**Comment by satoqz** [comment]
Can you provide more information on when exactly the error occurs? I have a guess but it'd make fixing a lot easier :)

**Comment by KREATIV-LSH** [comment]
I started VS Code but it didn`t load any extensions, so i ran the command for loading all extensions and then the command to show all running extensions and VS Code said that there was an Error running this extension.

**Comment by satoqz** [comment]
Can't really reproduce the described behavior, if you'd like to you can provide clearer steps of the exact commands ran.

However the error `RPC_CONNECTION_TIMEOUT` can only come from vscode having trouble connecting to the discord client, most likely because the discord client is not actually running. It throws an error because there is nothing to catch the rejected promise which i can easily update and fix.

**Comment by KREATIV-LSH** [comment]
OMG im so stupid i had Discord running in an other VM

**Comment by satoqz** [comment]
Still my fault for not catching the promise. You're not stupid, thank you for reporting the issue :)

**Comment by satoqz** [comment]
What im saying is that no actual error should be thrown as its expected behavior for a discord client not to be reachable which should therefore be ignored if it is the case instead of showing an annoying error to the user's extension logs.
