### ISSUE TITLE
Icon for AWK Files

### ISSUE THREAD

**Issue by diskxo** [satoqz/vscode-discord#99]
Can you add an icon for .awk files? Thanks ^^

**Comment by satoqz** [comment]
Would like to do so, though i don't know which sort of logo to choose for awk. Afaik there's no real logo associated with it, the best option might be going with the plain GNU logo. Any suggestions?

**Comment by diskxo** [comment]
VSCode uses this general terminal icon. If you want you can use it.
![image](https://user-images.githubusercontent.com/64780086/115426613-f475e980-a200-11eb-9fe9-a380ad3bbdf5.png)
